export const VALID_SERVICES: string[] = [
  'Adolescent Health',
  'Animal Bite Clinic',
  'Blood Bank',
  'Clinical Chemistry',
  'Clinical Microscopy',
  'Consultation',
  'Dental',
  'Dermatology',
  'Dialysis',
  'ECG',
  'ENT',
  'Emergency',
  'Eye Center',
  'Family Planning',
  'General Medicine',
  'HIV Treatment',
  'Hematology',
  'Immunization',
  'Internal Medicine',
  'Laboratory',
  'Maternal Care',
  'Mental Health',
  'Nutrition Services',
  'OB-GYN',
  'Pediatrics',
  'Primary Care',
  'Radiology',
  'Stroke Unit',
  'Surgery',
  'Trauma Care',
  'X-ray',
];
